# Generated by Django 4.0.1 on 2022-02-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_pair_symbol', models.CharField(max_length=10)),
                ('symbol_avg_price', models.FloatField()),
                ('api_dt', models.DateTimeField()),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPairHash',
            fields=[
                ('trading_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='binance_app.tradingpair')),
                ('hash', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
